#!/usr/bin/env bash
# TODO: All the paths need to change on final
## TO USE THIS SCRIPT PASTE THE FOLLOWING INTO THE TERMINAL:

# bash -c "$(curl -s https://raw.githubusercontent.com/wballard/starphleet/master/webinstall)"

##############################################################################
## Author:          Benjamin Hudgens
## Date:            March 18, 2015
##
## Description:     Fully Deploy starphleet from the command line
##
##############################################################################
## Locations to this repo

##############################################################################
## Main Foo
##############################################################################

apt update -y

apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

apt update -y
apt install -y docker-ce jq python parallel awscli

STARDOCK_INSTALL_DIR="/var/stardock"

mkdir -p "${STARDOCK_INSTALL_DIR}"
git clone 'https://github.com/bhudgens/stardock.git' "${STARDOCK_INSTALL_DIR}"

pushd "${STARDOCK_INSTALL_DIR}" > /dev/null

cp -R "${STARDOCK_INSTALL_DIR}/overlays/host"/* /
